### PR TITLE
Minor typo fix

### PR DESCRIPTION
**Pull request by xkcdjerry**

### CODE REVIEW

**Comment by uuk0** [comment]
Looks good to me, but we could add an reference to the launcher for automated download & update

**Comment by xkcdjerry** [comment]
Wait a mo

**Comment by xkcdjerry** [comment]
Wait, HOW do I use the launcher???(I have not used it before...)

**Comment by xkcdjerry** [comment]
We could use a wiki or a "docs" resptory, and move the "docs" folder there...

**Comment by uuk0** [comment]
download the code from the repo and simply run __main__.py. it will download the latest marked as "to download" revision of these repo (found in the Index-repo) and extract it and run it for you. It will also install all dependencies needed on startup

**Comment by xkcdjerry** [comment]
Emm, so, on a new relese, you add the new repo and tag it by hand?

**Comment by uuk0** [comment]
There is also an option to download the latest version, but yes, this it what I have done before

I can change it if you know an better option

**Comment by xkcdjerry** [comment]
First, can you modfiy the lanucher to only save the newest and the newest stable in the json file?

**Comment by uuk0** [comment]
In which repo do you mean?
I can change the index file in the Index repo to point only to two versions or
the launcher repo to have in itself the two versions as an json file

**Comment by xkcdjerry** [comment]
(The Index repo)You don't have to save the latest release, it is automatily gotten when you visit the download index

**Comment by uuk0** [comment]
Yes, this will work, thank you for your idea, I will change it

**Comment by xkcdjerry** [comment]
And you use two branches:"dev" and "stable" to make the Index unnessory

**Comment by uuk0** [comment]
Yes, good idea, I will change this

**Comment by xkcdjerry** [comment]
One last thing: I think we should maintaining a wiki or a Docs resptory, I am already at a lost in soooooo much files

**Comment by uuk0** [comment]
I've created one and I will start soon writing information
Can you please give me an example of how you would expect these doc-files to look like?

**Comment by xkcdjerry** [comment]
(in file somename.md)(feel free to use markup as long as the programs are plaintext)
->insert docs about this module
class SomeThing:
     ->insert docs about this class
     def ouch(self):
        ->insert docs about this methed
        (no need to insert the code)
def aaa(a):
    ->insert docs about aaa

**Comment by uuk0** [comment]
Ok, thank you

**Comment by xkcdjerry** [comment]
I suggest you can use files with the same name and path as the programs(and data) and change the extion to md(see my docs folder)

**Comment by uuk0** [comment]
Ok, I will have a look at it

**Pull request merged**
